bookings/urls.py
from django.urls import path

from bookings.views import SeatProcessor

urlpatterns = [
    path('data-processor/', SeatProcessor.as_view(), name='data-processor'),
]

tredes/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from .views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('page-not-found/', TemplateView.as_view(template_name='404_.html'), name='404_'),
    path('', TemplateView.as_view(template_name='index.html'), name='homepage'),
    path('data-booking-handler/', include(('bookings.urls', 'bookings-url'), namespace='bookings-url')),
    path('trips/', include(('trips.urls', 'trips-url'), namespace='trips-url')),
    path('account/', include(('accounts.urls', 'account-url'), namespace='account-url')),
    path('api/auth/', include(('accounts.api.urls', 'api-auth'), namespace='api-auth')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trips/urls.py
from django.urls import path

from trips.views import TripList, TripDetails

urlpatterns = [
    path('', TripList.as_view(), name='trip-list'),
    path('<slug:slug>/details/', TripDetails.as_view(), name='trip-detail'),
]

trips/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
from django.db.models import Q
from django.db.models.signals import post_save
from django.urls import reverse

from bus.models import Bus
from tredes.utils import unique_key_generator

User = get_user_model()


class TripsQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def search(self, query):
        lookups = (Q(from_locale__icontains=query) | Q(to_locale__icontains=query) | Q(bus__icontains=query))
        return self.filter(lookups).distinct()


class TripsManager(models.Manager):
    def get_queryset(self):
        return TripsQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def get_by_id(self):
        qs = self.get_queryset().filter(id=id)
        if qs.count == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().active().search(query)


class Trips(models.Model):
    from_locale = models.CharField(max_length=300)
    to_locale = models.CharField(max_length=300)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=5000)
    active = models.BooleanField(default=True)
    trip_time = models.DateTimeField(blank=True, null=True)
    ticket_key = models.CharField(max_length=100, blank=True, null=True)
    available_seats = models.IntegerField(blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = TripsManager()

    # reverse relationship
    # bus_set = Bus.trips_set.all().count()

    class Meta:
        db_table = "trips"
        verbose_name = "trips"
        verbose_name_plural = "trips"

    def __str__(self):
        return self.from_locale

    def get_absolute_url(self):
        return reverse("trips-url:trip-detail", kwargs={"slug": self.slug})


def ticket_key_post_save_receiver(sender, created, instance, *args, **kwargs):
    print(sender, instance, created)
    if created:
        if not instance.available_seats:
            instance.available_seats = instance.bus.seater
            instance.save()
        if not instance.ticket_key:
            instance.ticket_key = unique_key_generator(instance)
            instance.save()
    elif instance.ticket_key is None:
        instance.ticket_key = unique_key_generator(instance)
        instance.save()
    else:
        pass


post_save.connect(ticket_key_post_save_receiver, sender=Trips)

trips/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.utils import timezone
from django.views.generic import ListView, DetailView

from bookings.models import Booking
from trips.models import Trips


class TripList(LoginRequiredMixin, ListView):
    queryset = Trips.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(TripList, self).get_context_data(*args, **kwargs)
        context['currentDateTime'] = timezone.now()

        return context

    def get_queryset(self):
        return Trips.objects.filter(active=True)


class TripDetails(LoginRequiredMixin, DetailView):
    queryset = Trips.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(TripDetails, self).get_context_data(*args, **kwargs)
        context['booked_seats'] = self.get_object().bus.seater - self.get_object().available_seats
        context['currentDateTime'] = timezone.now()
        return context

    def render_to_response(self, context, **response_kwargs):
        if context:
            try:
                if self.get_object().trip_time <= timezone.now() or self.get_object().available_seats == 0:
                    messages.warning(self.request, "Booking For This Trip Has Expired!")
                booking_obj = Booking.objects.get(user=self.request.user, key=self.get_object().ticket_key)
                if booking_obj and booking_obj.token:
                    messages.info(self.request, "You have booked this trip already!")
            except:
                pass
        return super(TripDetails, self).render_to_response(context, **response_kwargs)

    def get_object(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        try:
            instance = Trips.objects.get(slug=slug)
        except Trips.DoesNotExist:
            return redirect(reverse('404_'))
        except Trips.MultipleObjectsReturned:
            qs = Trips.objects.filter(slug=slug)
            instance = qs.first()
        except:
            return redirect(reverse('404_'))
        return instance

trips/templates/trips/trips_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ object }} {% endblock title %}

{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>
                <i class="fas fa-car-alt"></i> {{ object }} <i class="fas fa-arrow-right"></i>
                <i class="fas fa-house-damage"></i> {{ object.to_locale }}
            </h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">{{ object }} <i class="fas fa-arrow-right"></i> {{ object.to_locale }}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Book Trip From <i class="fas fa-car-alt"></i> {{ object }} <i class="fas fa-arrow-right"></i>
                <i class="fas fa-house-damage"></i> {{ object.to_locale }}</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fas fa-minus"></i></button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fas fa-times"></i></button>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
              <div class="row">
                <div class="col-12 col-sm-4">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">Total Seats On {{ object.bus.name }}</span>
                      <span class="info-box-number text-center text-muted mb-0">{{ object.bus.seater }}</span>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-sm-4">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">Booked Seats On {{ object.bus.name }}</span>
                      <span class="info-box-number text-center text-muted mb-0">{{ booked_seats }}</span>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-sm-4">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">Available Seats </span>
                      <span class="info-box-number text-center text-muted mb-0">{{ object.available_seats }} <span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <h4>Book A Seat For This Trip</h4>
                    <div class="post">
                      <div class="user-block">
                        <img class="img-circle img-bordered-sm" src="{{ request.user.profile.get_image }}" alt="user image">
                        <span class="username">
                          <a href="#">{{ request.user.profile.get_name }}</a>
                        </span>
                      </div>
                      <!-- /.user-block -->
                      <div class="col-6 input-group mb-3">
                          <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-chair"></i></span>
                          </div>
                          <input class="form-control" id="seatQuantity" type="number" value="1" min="1" max="{{ object.available_seats }}" step="1">
                      </div>
                      <div class="col-6 input-group mb-3">
                          <img class="img-responsive" width="300px" height="200px" src="{{ object.bus.image.url }}">
                      </div>
                      <p class="col-6">
                          {% if object.available_seats == 0 or object.trip_time <= currentDateTime %}
                            <button type="Submit" id="bookSeatDisabled" class="btn btn-block btn-outline-primary btn-sm disabled">Cannot Book</button>
                          {% else %}
                            <button type="Submit" id="bookSeat" class="btn btn-block btn-outline-primary btn-sm">Book</button>
                          {% endif %}
                      </p>


                    </div>
                </div>
              </div>
            </div>
            <div class="col-12 col-md-12 col-lg-4 order-1 order-md-2">
              <h3 class="text-primary"><i class="fas fa-building"></i> {{ object.bus.company_alias.name }}</h3>
              <p class="text-muted">
                  {{ object.bus.company_alias.description }}
              </p>
              <div>
                  <img class="img-responsive" width="400px" height="200px" src="{{ object.bus.company_alias.image.url }}">
              </div>
              <br>
              <div class="text-muted">
                <p class="text-sm">Alias Company
                  <b class="d-block">{{ object.bus.company_alias.name }}</b>
                </p>
                <p class="text-sm">Contact Support
                  <b class="d-block"><i class="fas fa-envelope-open"></i> support@tredes.com.ng</b>
                </p>
              </div>

              <h5 class="mt-5 text-muted">Having Issues ?</h5>
              <ul class="list-unstyled">
                <li>
                  <a href="" class="btn-link text-secondary"><i class="far fa-fw fa-envelope"></i> Contact {{ object.bus.company_aias.name }}</a>
                </li>
                <li>
                  <a href="" class="btn-link text-secondary"><i class="far fa-fw fa-image "></i> Book From {{ object.bus.company_alias.name }}</a>
                </li>
              </ul>
              <div class="text-center mt-5 mb-3">
                <a href="#" class="btn btn-sm btn-warning">File A Report</a>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
    <script src="https://cdn.tredes.com.ng/plugins/jquery/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.js"></script>
    <!-- SweetAlert2 -->
    <script src="https://cdn.tredes.com.ng/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="https://cdn.tredes.com.ng/plugins/toastr/toastr.min.js"></script>
    <!-- AdminLTE App -->
    <script src="https://cdn.tredes.com.ng/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="https://cdn.tredes.com.ng/dist/js/demo.js"></script>
    <script>
        $( function () {
            $(document).ready(function () {
                {% if messages %}
                    {% for message in messages %}
                        $(document).Toasts('create', {
                            class: {% if message.tags %}'bg-warning'{% endif %},
                            title: {% if message.tags %}'Booking Warning'{% endif %},
                            subtitle: 'Warning!',
                            body: {% if message.tags %}'{{ message }}'{% endif %}
                          });
                        setTimeout(function () {
                            window.location.replace("{% url 'trips-url:trip-list' %}");
                        }, 4000);
                    {% endfor %}
                {% endif %}

                let bookingButton = $('#bookSeat');

                function displaySubmitting(submitBtn, defaultText, doSubmit) {
                    if (doSubmit) {
                        submitBtn.addClass("disabled");
                        submitBtn.html("<i class='fa fa-spin fa-spinner'></i> Processing");
                    } else {
                        submitBtn.removeClass("disabled");
                        submitBtn.add(defaultText);
                    }
                }

                function tokenGenarator(length) {
                    let result = '';
                    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
                    const charactersLength = characters.length;
                    for ( var i = 0; i < length; i++ ) {
                      result += characters.charAt(Math.floor(Math.random() * charactersLength));
                   }
                   return result;
                }

                bookingButton.click(function (event) {
                    event.preventDefault();

                    // Ajax token parser
                    function getCookie(name) {
                        var cookieValue = null;
                        if (document.cookie && document.cookie !== '') {
                            var cookies = document.cookie.split(';');
                            for (var i = 0; i < cookies.length; i++) {
                                var cookie = jQuery.trim(cookies[i]);
                                // Does this cookie string begin with the name we want?
                                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                    break;
                                }
                            }
                        }
                        return cookieValue;
                    }
                    var csrftoken = getCookie('csrftoken');

                    function csrfSafeMethod(method) {
                        // these HTTP methods do not require CSRF protection
                        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                    }
                    $.ajaxSetup({
                        beforeSend: function(xhr, settings) {
                            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                            }
                        }
                    });

                    const bookingData = {
                        "key": '{{ object.ticket_key }}',
                        "seats": $('#seatQuantity').val(),
                        "token": tokenGenarator(7),
                    };

                    displaySubmitting(bookingButton, "", true);
                    $.ajax({
                        method: 'POST',
                        url: '{% url "bookings-url:data-processor" %}',
                        data: bookingData,
                        contentType: 'application/x-www-form-urlencoded',
                        dataType: 'json',

                        success: function (data) {
                            console.log(data);
                            $(document).Toasts('create', {
                                class: 'bg-success',
                                body: 'Please Print Booking Data From Events as ticket',
                                title: 'Booking Successful!',
                                subtitle: 'Booking For Trip Successfully!',
                                image: '{{ request.user.profile.get_image }}',
                                imageAlt: 'User Image',
                            });
                            setTimeout(function(){
                                displaySubmitting(bookingButton, 'Book', false)
                            }, 500);
                            setTimeout(function () {
                                window.location.replace("{% url 'dashboard' %}");
                            }, 5000);
                        }, error: function (error) {
                            $(document).Toasts('create', {
                                class: 'bg-danger',
                                title: 'Oops! Booking Failed',
                                subtitle: 'Error In Booking!',
                                body: 'Error has occurred during your booking!'
                              });
                            displaySubmitting(bookingButton, 'Book', false)
                        }
                    })

                })
            })
        } (jQuery))
    </script>

{% endblock content %}