accounts/api/urls.py
from django.urls import path, include
from rest_framework_jwt.views import refresh_jwt_token, obtain_jwt_token # accounts app

from .views import AuthAPIView, RegisterAPIView

urlpatterns = [
    path('', AuthAPIView.as_view(), name='login-api'),
    path('register/', RegisterAPIView.as_view(), name='register-api'),
    path('jwt/', obtain_jwt_token),
    path('jwt/refresh/', refresh_jwt_token),
]

accounts/api/user/urls.py
from django.urls import path, include

from .views import UserDetailAPIView

urlpatterns = [
    path('<username>/', UserDetailAPIView.as_view(), name='detail'),
]

accounts/urls.py
from django.urls import path

from .views import RegisterView, LoginView, UserProfileView

urlpatterns = [
    path('sign-up/', RegisterView.as_view(), name='register'),
    path('sign-in/', LoginView.as_view(), name='login'),
    path('profile/<slug:slug>/', UserProfileView.as_view(), name='profile'),
]

tredes/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from .views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('page-not-found/', TemplateView.as_view(template_name='404_.html'), name='404_'),
    path('', TemplateView.as_view(template_name='index.html'), name='homepage'),
    path('data-booking-handler/', include(('bookings.urls', 'bookings-url'), namespace='bookings-url')),
    path('trips/', include(('trips.urls', 'trips-url'), namespace='trips-url')),
    path('account/', include(('accounts.urls', 'account-url'), namespace='account-url')),
    path('api/auth/', include(('accounts.api.urls', 'api-auth'), namespace='api-auth')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trips/urls.py
from django.urls import path

from trips.views import TripList, TripDetails

urlpatterns = [
    path('', TripList.as_view(), name='trip-list'),
    path('<slug:slug>/details/', TripDetails.as_view(), name='trip-detail'),
]

accounts/models.py
import random
import os

from django.db import models
from django.db.models.signals import pre_save, post_save
from django.contrib.auth import get_user_model
from cloudinary.models import CloudinaryField
from django.dispatch import receiver
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from tredes.utils import unique_slug_generator

# Create your models here.

User = get_user_model()


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1, 3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "profile/{new_filename}/{final_filename}".format(
        new_filename=new_filename,
        final_filename=final_filename
    )


GENDER_CHOICES = (('M', 'Male'), ('F', 'Female'),)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    uuid = models.CharField(max_length=100, blank=True, null=True,
                            help_text="Copy This Data From Firebase UUID AccountKit")
    bio = models.TextField(blank=True, null=True)
    phone = PhoneNumberField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True)
    birthday = models.DateField(null=True, blank=True)
    image = CloudinaryField(upload_image_path, null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "profile"
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"
        unique_together = ('phone', 'slug')

    def __str__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        return reverse('account-url:profile', kwargs={'slug':self.slug})

    def age(self):
        import datetime
        return int((datetime.date.today() - self.birthday).days / 365.25)

    def image_tag(self):
        from django.utils.html import escape, mark_safe
        return mark_safe('<img src="%s" width="100" height="100" />' % self.image.url)

    image_tag.short_description = 'Profile Image'
    image_tag.allow_tags = True

    def get_name(self):
        if self.user.first_name and self.user.last_name:
            caps_initials = "{} {}".format(self.user.first_name, self.user.last_name)
            caps_initials = caps_initials.title()
            return caps_initials
        return self.user.username

    def get_firebase_id(self):
        if self.uuid:
            return self.uuid
        return "GET UUID FROM TREDES FLEETS MOBILE"

    @property
    def get_image(self):
        if self.image:
            return self.image.url
        return "https://img.icons8.com/officel/2x/user.png"


def post_save_profile_receiver(sender, created, instance, *args, **kwargs):
    if created:
        if not instance.slug:
            instance.slug = unique_slug_generator(instance)
            instance.save()


post_save.connect(post_save_profile_receiver, sender=Profile)

accounts/api/user/views.py
from django.contrib.auth import get_user_model
from rest_framework import generics
from .serializers import UserDetailSerializer

User = get_user_model()


class UserDetailAPIView(generics.RetrieveAPIView):
    queryset = User.objects.filter(is_active=True)
    serializer_class = UserDetailSerializer
    lookup_field = 'username'

    def get_serializer_context(self):
        return {'request': self.request}

accounts/api/views.py
from django.contrib.auth import authenticate, get_user_model
from django.db.models import Q
from rest_framework import generics, permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework_jwt.settings import api_settings

from .permissions import AnonPermissionOnly
from .serializers import UserRegisterSerializer

jwt_payload_handler = api_settings.JWT_PAYLOAD_HANDLER
jwt_encode_handler = api_settings.JWT_ENCODE_HANDLER
jwt_response_payload_handler = api_settings.JWT_RESPONSE_PAYLOAD_HANDLER

User = get_user_model()


class AuthAPIView(APIView):
    permission_classes = [AnonPermissionOnly]

    def post(self, request, *args, **kwargs):
        # print(request.user)
        if request.user.is_authenticated:
            return Response({'detail': 'You are already authenticated'}, status=400)
        data = request.data
        username = data.get('username')  # username or email address
        password = data.get('password')
        qs = User.objects.filter(
            Q(username__iexact=username) |
            Q(email__iexact=username)
        ).distinct()
        if qs.count() == 1:
            user_obj = qs.first()
            if user_obj.check_password(password):
                user = user_obj
                payload = jwt_payload_handler(user)
                token = jwt_encode_handler(payload)
                response = jwt_response_payload_handler(token, user, request=request)
                return Response({"username":username, "password":password, "token":token}, status=200)

        return Response({"detail": "Invalid credentials"}, status=401)


class RegisterAPIView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserRegisterSerializer
    permission_classes = [AnonPermissionOnly]

    def get_serializer_context(self, *args, **kwargs):
        return {"request": self.request}

accounts/views.py
from django.contrib.auth import get_user_model, authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from django.views.generic import DetailView
from django.views.generic.base import View

from accounts.models import Profile

User = get_user_model()


# Create your views here.


class RegisterView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse('404_'))
        return render(request, template_name='accounts/register.html')


class LoginView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse('404_'))
        return render(request, template_name='accounts/login.html')

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            data = request.POST
            username = data['username']
            password = data['password']
            user_qs = User.objects.filter(username__iexact=username)
            if user_qs.exists():
                user = authenticate(username=username, password=password)
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                return JsonResponse({'message': 'Logged In Successfully!'}, status=200)
            return JsonResponse({'message': 'Error With User!'}, status=400)
        return JsonResponse({'message': 'Method Not Allowed!'}, status=400)


class UserProfileView(LoginRequiredMixin, DetailView):
    queryset = Profile.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(UserProfileView, self).get_context_data(*args, **kwargs)
        context['user_bookings'] = self.request.user.booking_set.all()
        context['currentTime'] = timezone.now()
        return context

    def render_to_response(self, context, **response_kwargs):
        if context:
            user_obj = str(self.get_object())
            if user_obj != self.request.user.username:
                return HttpResponseRedirect(reverse('404_'))
        return super(UserProfileView, self).render_to_response(context, **response_kwargs)

    def get_object(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        try:
            instance = Profile.objects.get(slug=slug)
        except Profile.DoesNotExist:
            return redirect(reverse('404_'))
        except Profile.MultipleObjectsReturned:
            qs = Profile.objects.filter(slug=slug)
            instance = qs.first()
        except:
            return redirect(reverse('404_'))
        return instance

accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Tredes Fleets | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
  <!-- Ionicons -->
  <link rel="stylesheet" type="text/css" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" type="text/css" href="https://cdn.tredes.com.ng/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" type="text/css" href="https://cdn.tredes.com.ng/dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" type="text/css" rel="stylesheet">
  <!-- alert style shit from jQuery -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.css">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>TREDES</b> FLEETS</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>

      <form class="loginForm" action="{% url 'api-auth:login-api' %}" method="POST"> {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" id="username" placeholder="Username" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-person-booth"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" id="password" placeholder="Password" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mb-1">
        <a href="forgot-password.html">I forgot my password</a>
      </p>
      <p class="mb-0">
        <a href="{% url 'account-url:register' %}" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="https://cdn.tredes.com.ng/plugins/jquery/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.js"></script>
<!-- Bootstrap 4 -->
<script src="https://cdn.tredes.com.ng/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="https://cdn.tredes.com.ng/dist/js/adminlte.min.js"></script>

<script>
    $( function () {
        'use strict';
        $(document).ready(function () {
            // Initialize data
            var loginForm = $('.loginForm');
            var loginFormMethod = loginForm.attr('method');
            var loginFormEndpoint = loginForm.attr('action');

            function displaySubmitting(submitBtn, defaultText, doSubmit) {
                if (doSubmit) {
                    submitBtn.addClass("disabled");
                    submitBtn.html("<i class='fa fa-spin fa-spinner'></i> Sending Data..");
                } else {
                    submitBtn.removeClass("disabled");
                    submitBtn.add(defaultText);
                }
            }

            var loginFormSubmitBtn = loginForm.find("[type='submit']");
            var loginFormSubmitBtnText = loginFormSubmitBtn.text();

            loginForm.submit(function (event) {
                event.preventDefault();
                // using jQuery
                function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie !== '') {
                        var cookies = document.cookie.split(';');
                        for (var i = 0; i < cookies.length; i++) {
                            var cookie = jQuery.trim(cookies[i]);
                            // Does this cookie string begin with the name we want?
                            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                }
                var csrftoken = getCookie('csrftoken');

                function csrfSafeMethod(method) {
                    // these HTTP methods do not require CSRF protection
                    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                }
                $.ajaxSetup({
                    beforeSend: function(xhr, settings) {
                        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        }
                    }
                });

                var loginFormData = {
                    "username": $('#username').val(),
                    "password": $('#password').val(),
                };
                console.log(loginFormData);
                var thisForm = $(this);

                displaySubmitting(loginFormSubmitBtn, "", true);

                $.ajax({
                        method: loginFormMethod,
                        url: loginFormEndpoint,
                        data: loginFormData,
                        contentType: 'application/x-www-form-urlencoded',
                        dataType: 'json',

                        success: function (data) {
                            loginForm[0].reset();
                            console.log(data);
                            // perform ajax call to view server
                            $.ajax({
                                method: "POST",
                                url: "{% url 'account-url:login' %}",
                                data: data,
                                contentType: 'application/x-www-form-urlencoded',
                                dataType: 'json',

                                success: function (data) {
                                    console.log(data);
                                    $.alert({
                                        title: 'Success!',
                                        content: 'Logged In Successfully!',
                                        theme: 'modern',
                                    });
                                    setTimeout(function(){
                                        displaySubmitting(loginFormSubmitBtn, loginFormSubmitBtnText, false)
                                    }, 500);
                                    setTimeout(function () {
                                        window.location.replace("{% url 'dashboard' %}");
                                    }, 5000);
                                }
                            });
                        }, error: function (error) {
                            console.log(error);
                            // var errorData = error.responseJSON('detail');
                            loginForm[0].reset();
                            $.alert({
                                icon: 'fa fa-warning',
                                title: 'Oops!',
                                content: "Error During Sign In!",
                                theme: 'white',
                                backgroundDismiss: true,
                                animationSpeed: 2000,
                            });
                            displaySubmitting(loginFormSubmitBtn, loginFormSubmitBtnText, false);
                        }
                    })
            })
        })
    } (jQuery));
</script>

</body>
</html>

accounts/templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Tredes Fleets | Registration Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" type="text/css" href="https://cdn.tredes.com.ng/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" type="text/css" href="https://cdn.tredes.com.ng/dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- jQuery Date Picker UI -->
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="/"><b>TREDES</b> Fleets</a>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">TREDES FLEETS Passenger Service</p>

      <form class="registerForm" action="{% url 'api-auth:register-api' %}" method="POST"> {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" id="username" placeholder="Username" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="text" class="form-control" id="first_name" placeholder="First name" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="text" class="form-control" id="last_name" placeholder="Last name" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="text" class="form-control" id="phone" placeholder="Phone: +23480XXXXXXXX" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-phone"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="email" class="form-control" id="email" placeholder="Email" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control" id="password" placeholder="Password" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" name="confirm_password" class="form-control" id="confirm_password" placeholder="Retype password" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="agreeTerms" name="terms" value="agree">
              <label for="agreeTerms">
               I agree to the <a href="#">terms</a>
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" id="registerButton" class="btn btn-primary btn-block">Register</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <a href="{% url 'account-url:login' %}" class="text-center">I already have a membership</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="https://cdn.tredes.com.ng/plugins/jquery/jquery.min.js"></script>

<!-- Bootstrap 4 -->
<script src="https://cdn.tredes.com.ng/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="https://cdn.tredes.com.ng/dist/js/adminlte.min.js"></script>

  <script>
    $( function() {
        'use strict';
        // $("#age").datepicker();

        $(document).ready(function () {
            // Initialize form data
            var registerForm = $(".registerForm");
            var registerFormMethod = registerForm.attr("method");
            var registerFormEnpoint = registerForm.attr("action");
            
            function displaySubmitting(submitBtn, defaultText, doSubmit) {
                if (doSubmit) {
                    submitBtn.addClass("disabled");
                    submitBtn.html("<i class='fa fa-spin fa-spinner'></i> Sending Data..");
                } else {
                    submitBtn.removeClass("disabled");
                    submitBtn.add(defaultText);
                }
            }

            function handleButton(submitBtn, doSubmit) {
                if (doSubmit){
                    submitBtn.addClass("disabled");
                } else {
                    submitBtn.removeClass("disabled");
                }
            }

            var registerFormSubmitBtn = registerForm.find("[type='submit']");
            var registerFormSubmitBtnText = registerFormSubmitBtn.text();

            // disable button on page-load
            handleButton(registerFormSubmitBtn, true);

            var checker = document.getElementById('agreeTerms');
            checker.onchange = function(){
                if (this.checked){
                    // perform our custom action here
                    handleButton(registerFormSubmitBtn, false); // activates button onCheck!
                    registerForm.submit(function (event) {
                        event.preventDefault();

                        // using jQuery
                        function getCookie(name) {
                            var cookieValue = null;
                            if (document.cookie && document.cookie !== '') {
                                var cookies = document.cookie.split(';');
                                for (var i = 0; i < cookies.length; i++) {
                                    var cookie = jQuery.trim(cookies[i]);
                                    // Does this cookie string begin with the name we want?
                                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                        break;
                                    }
                                }
                            }
                            return cookieValue;
                        }
                        var csrftoken = getCookie('csrftoken');

                        function csrfSafeMethod(method) {
                            // these HTTP methods do not require CSRF protection
                            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                        }
                        $.ajaxSetup({
                            beforeSend: function(xhr, settings) {
                                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                                }
                            }
                        });

                        // var registerFormData = registerForm.serialize(); // do not serialize the data, drf would do that
                        var registerFormData = {
                            "username": $('#username').val(),
                            "first_name": $('#first_name').val(),
                            "last_name": $('#last_name').val(),
                            "phone": $('#phone').val(),
                            "email": $('#email').val(),
                            "password": $('#password').val(),
                            "confirm_password": $('#confirm_password').val(),
                        };
                        var thisForm = $(this);

                        displaySubmitting(registerFormSubmitBtn, "", true);

                        $.ajax({
                        method: registerFormMethod,
                        url: registerFormEnpoint,
                        data: registerFormData,
                        contentType: 'application/x-www-form-urlencoded',
                        dataType: 'json',

                        success: function (data) {
                            registerForm[0].reset();
                            console.log(data);
                            $.alert({
                                title: 'Success!',
                                content: 'Registration for '+data+' was successful',
                                theme: 'modern',
                            });
                            setTimeout(function(){
                                displaySubmitting(registerFormSubmitBtn, registerFormSubmitBtnText, false)
                            }, 5000)
                        }, error: function (error) {
                            console.log(error);
                        }
                    })

                    })
                } else {
                    handleButton(registerFormSubmitBtn, true);
                }
            }
        })
    } (jQuery));
  </script>

</body>
</html>